### PR TITLE
Branch Merge and Addition of Event Listener 

### PR DESCRIPTION
**Pull request by chowafu**
### **Added:**
- Initial Event Listener files for login, failed login, logout, and lockout* events for audit logging.

### **In progress:**
- Restructuring of `audits` table to accommodate new event listeners.

### CODE REVIEW

**Comment by externalip** [comment]
maya boss paguwi

**Comment by chowafu** [comment]
Reported to HR

**Comment by chowafu** [comment]
Note: Event Listeners are not supposed to work yet. 

Either create a new Audits table or Comment out the codes of `handle(): void` located at `App/Listeners/LogSuccessfulLogin.php`
image

Not doing so may result the login function to fail.

**Review by externalip — APPROVED** [review]
LGTM

**Pull request merged**
